[general]
# The owners of the bot
owners = [158280426551640064]
# Time to wait for user interactions in seconds
interaction_timeout = 60
# Maximum size of the command history for autocompletion per user and command
command_history_size = 500
# Maximum amount of autocomplete suggestions to send back to the user
autocomplete_size = 10
# Default cooldown for up-/downvotes in seconds
default_cooldown = 30
# Amount of users per leaderboard page
leaderboard_size = 10
# Titles for the leaderboard ranks
leaderboard_titles = ["👑", "⚔️", "🗡️"]

[commands]
# Global
# For the permission field, use https://discordapi.com/permissions.html
[commands.about]
command_type = "About"
description = "Display information about the bot."
default_permission = true

[commands.info]
command_type = "Info"
description = "Display information about certain modules."
default_permission = true

[commands.info.options.module]
kind = "String"
description = "The module to query."
required = true
choices = ["Owner", "Utility", "Score", "ReactionRoles"]

[commands.module]
command_type = "Module"
description = "Update the activated modules on this server."
default_permission = false
permission = "8"

[commands.module.options.action]
kind = "String"
description = "What to do."
required = true
choices = ["enable", "disable", "remove"]

[commands.module.options.module]
kind = "String"
description = "The module to update."
required = true
choices = ["Owner", "Utility", "Score", "ReactionRoles"]

[commands.ping]
command_type = "Ping"
description = "Ping the bot."
default_permission = true

# Bot management
[commands.guild]
command_type = "Guild"
description = "Manage guilds created by the bot."
module = "Owner"
default_permission = false
owner = true

[commands.guild.options.action]
kind = "String"
description = "What to do."
required = true
choices = ["create", "list"]

[commands.say]
command_type = "Say"
description = "Make the bot say something."
module = "Owner"
default_permission = false
owner = true

[commands.say.options.title]
kind = "String"
description = "The title of the embed."
required = true
autocomplete = true

[commands.say.options.content]
kind = "String"
description = "The content of the embed."
required = true
autocomplete = true

[commands.sql]
command_type = "Sql"
description = "Execute a SQL query."
module = "Owner"
default_permission = false
owner = true

[commands.sql.options.query]
kind = "String"
description = "The SQL query to execute."
required = true
autocomplete = true

# Utility
[commands.clear]
command_type = "Clear"
description = "Clear a certain amount of recent messages."
module = "Utility"
default_permission = false
permission = "8192"

[commands.clear.options.count]
kind = "Integer"
description = "The amount of messages to delete."
required = true
min_value = 1
max_value = 100

[commands.clear.options.before]
kind = "String"
description = "The message id from which to start deleting messages."

# Score
[commands.moderate]
command_type = "Moderate"
description = "Automatically pin/delete messages based on their votes."
module = "Score"
default_permission = false
permission = "8"

[commands.moderate.options.moderation]
kind = "String"
description = "What to do to the message after reaching the score."
required = true
choices = ["pin", "delete"]

[commands.moderate.options.score]
kind = "Integer"
description = "The score to reach (disable the moderation if no score is given)."

[commands.cooldown]
command_type = "Cooldown"
description = "Define a custom reaction cooldown for certain roles."
module = "Score"
default_permission = false
permission = "8"

[commands.cooldown.options.role]
kind = "Role"
description = "The role to update."
required = true

[commands.cooldown.options.cooldown]
kind = "Integer"
description = "The cooldown in seconds (reset the cooldown if no cooldown is given)."
min_value = 0

[commands.emoji]
command_type = "Emoji"
description = "Manage which emojis should count as up- and downvotes."
module = "Score"
default_permission = false
permission = "8"

[commands.emoji.options.action]
kind = "String"
description = "What to do."
required = true
choices = ["add upvote", "add downvote", "remove"]

[commands.emoji.options.emoji]
kind = "String"
description = "The emoji to update."
required = true

[commands.given]
command_type = "Given"
description = "Display stats about the votes given to other users."
module = "Score"
default_permission = true

[commands.given.options.user]
kind = "User"
description = "The user to query."

[commands.levelup]
command_type = "LevelUp"
description = "Manage the roles assigned by the bot on a certain score."
module = "Score"
default_permission = false
permission = "8"

[commands.levelup.options.action]
kind = "String"
description = "What to do."
required = true
choices = ["add", "remove"]

[commands.levelup.options.role]
kind = "Role"
description = "The role to update."
required = true

[commands.levelup.options.score]
kind = "Integer"
description = "The required score for the role."
required = true

[commands.rank]
command_type = "Rank"
description = "Display the rank of a user."
module = "Score"
default_permission = true

[commands.rank.options.user]
kind = "User"
description = "The user to query."

[commands.score]
command_type = "Score"
description = "Display the score of a user."
module = "Score"
default_permission = true

[commands.score.options.user]
kind = "User"
description = "The user to query."

[commands.top]
command_type = "Top"
description = "Display the users with the highest scores."
module = "Score"
default_permission = true

# Reaction Roles
[commands.reactionrole]
command_type = "ReactionRole"
description = "Manage the roles assigned when a user reacts on a certain message."
module = "ReactionRoles"
default_permission = false
permission = "8"

[commands.reactionrole.options.action]
kind = "String"
description = "What to do."
required = true
choices = ["add", "remove"]

[commands.reactionrole.options.role]
kind = "Role"
description = "The role to assign."
required = true

[commands.reactionrole.options.slots]
kind = "Integer"
description = "The maximum number of users which can hold the reaction-role at the same time."
min_value = 0
